
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.37.0.  DO NOT EDIT!
//*************************************************************************************

using System.Collections.Generic;

namespace XTC.FMP.MOD.VRLobby.LIB.Unity
{
    /// <summary>
    /// 大纲类的基类
    /// </summary>
    public class MyCatalogBase
    {
        /// <summary>
        /// 段
        /// </summary>
        public class Section
        {
            /// <summary>
            /// 段的名称
            /// </summary>
            public string name { get; set; } = "";

            /// <summary>
            /// 段的路径，支持/字符分割
            /// </summary>
            public string path { get; set; } = "";

            /// <summary>
            /// 实例
            /// </summary>
            public List<string> instanceS { get; set; } = new List<string>();

            /// <summary>
            /// 主体内容
            /// </summary>
            public string[] bodyS { get; set; } = new string[0];

            /// <summary>
            /// 键值对
            /// </summary>
            public Dictionary<string, string> kvS { get; set; } = new Dictionary<string, string>();
        }

        public Section[] sectionS { get; set; } = new Section[0];
    }
}

